"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  useJobReport,
  type JobReportEntry,
  type JobReportEntryType,
} from "@/lib/job-report";

function formatTimestamp(value: string) {
  return new Date(value).toLocaleString();
}

function renderTypeLabel(type: JobReportEntryType) {
  if (type === "fault") return "Fault";
  if (type === "parameter-change") return "Parameter Change";
  if (type === "pid") return "PID Snapshot";
  return "Note";
}

function downloadFile(filename: string, body: string, mime = "text/plain") {
  const blob = new Blob([body], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

function buildTextReport(
  title: string,
  siteName: string,
  equipment: string,
  technician: string,
  entries: JobReportEntry[]
) {
  const lines: string[] = [];
  lines.push(title || "Field Tech Report");
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  lines.push(`Site: ${siteName || "-"}`);
  lines.push(`Equipment: ${equipment || "-"}`);
  lines.push(`Technician: ${technician || "-"}`);
  lines.push(`Entries: ${entries.length}`);
  lines.push("");

  entries.forEach((entry, idx) => {
    lines.push(`${idx + 1}. ${renderTypeLabel(entry.type)} - ${entry.title}`);
    lines.push(`   Time: ${formatTimestamp(entry.createdAt)}`);
    if (entry.source) lines.push(`   Source: ${entry.source}`);
    if (entry.summary && entry.summary !== entry.title) lines.push(`   Summary: ${entry.summary}`);
    if (entry.fields && Object.keys(entry.fields).length > 0) {
      lines.push("   Details:");
      Object.entries(entry.fields).forEach(([key, value]) => {
        lines.push(`   - ${key}: ${value}`);
      });
    }
    lines.push("");
  });

  return lines.join("\n");
}

function buildPdf(
  title: string,
  siteName: string,
  equipment: string,
  technician: string,
  entries: JobReportEntry[]
) {
  return import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    const m = 20;              // page margin
    const cw = pw - m * 2;     // content width
    const headerY = 14;        // page header top
    const footerY = ph - 10;   // page footer baseline
    const bodyTop = 24;        // first content line (below page header)
    let y = bodyTop;

    const dark = [30, 41, 59] as const;      // slate-800
    const mid = [100, 116, 139] as const;     // slate-500
    const light = [148, 163, 184] as const;   // slate-400
    const bg = [248, 250, 252] as const;      // slate-50
    const brand = [59, 130, 246] as const;    // blue-500

    // Entry type colors (text, bg-fill)
    const typeColors: Record<JobReportEntryType, { text: readonly [number, number, number]; bg: readonly [number, number, number] }> = {
      fault:              { text: [185, 28, 28],  bg: [254, 242, 242] },   // red
      "parameter-change": { text: [30, 64, 175],  bg: [239, 246, 255] },   // blue
      pid:                { text: [21, 128, 61],   bg: [240, 253, 244] },   // green
      note:               { text: [100, 116, 139], bg: [248, 250, 252] },   // gray
    };

    const reportTitle = title || "Field Tech Report";

    function newPage() {
      doc.addPage();
      y = bodyTop;
    }

    function pageBreak(needed: number) {
      if (y + needed > footerY - 6) { newPage(); }
    }

    // ── Page header & footer (applied to all pages at end)
    function applyPageChrome() {
      const total = doc.getNumberOfPages();
      for (let i = 1; i <= total; i++) {
        doc.setPage(i);

        // ─ Header: brand mark left, report title right
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(...brand);
        doc.text("FieldKit Pro", m, headerY);

        if (i > 1) {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(7);
          doc.setTextColor(...mid);
          const rt = reportTitle;
          doc.text(rt, pw - m - doc.getTextWidth(rt), headerY);
        }

        // Header rule
        doc.setDrawColor(...brand);
        doc.setLineWidth(0.3);
        doc.line(m, headerY + 3, pw - m, headerY + 3);

        // ─ Footer: generated line left, page number right
        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.setTextColor(...light);
        doc.text("Generated by FieldKit Pro", m, footerY);

        const pg = `Page ${i} of ${total}`;
        doc.text(pg, pw - m - doc.getTextWidth(pg), footerY);
      }
    }

    // ── Report Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(...dark);
    const titleLines = doc.splitTextToSize(reportTitle, cw);
    doc.text(titleLines, m, y);
    y += titleLines.length * 8 + 2;

    // ── Generated date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...mid);
    doc.text(
      new Date().toLocaleDateString("en-US", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
      m,
      y
    );
    y += 9;

    // ── Metadata box
    const metaPairs = [
      ["Site", siteName],
      ["Equipment", equipment],
      ["Technician", technician],
    ].filter(([, v]) => v) as [string, string][];

    if (metaPairs.length > 0) {
      const rows = Math.ceil(metaPairs.length / 2);
      const rowH = 8;
      const boxH = rows * rowH + 6;
      doc.setFillColor(...bg);
      doc.roundedRect(m, y - 3, cw, boxH, 2, 2, "F");

      // Left border accent
      doc.setFillColor(...brand);
      doc.rect(m, y - 3, 1.2, boxH, "F");

      const colW = cw / 2;
      metaPairs.forEach(([label, value], i) => {
        const col = i % 2;
        const row = Math.floor(i / 2);
        const tx = m + 6 + col * colW;
        const ty = y + 1 + row * rowH;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(...mid);
        doc.text(label.toUpperCase(), tx, ty);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(...dark);
        const valText = doc.splitTextToSize(value, colW - 10);
        doc.text(valText[0], tx, ty + 3.5);
      });

      y += boxH + 6;
    }

    // ── Entries
    if (entries.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(...light);
      doc.text("No findings captured.", m, y);
    } else {
      // Section header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...mid);
      doc.text(`FINDINGS  (${entries.length})`, m, y);
      doc.setDrawColor(220, 224, 228);
      doc.setLineWidth(0.2);
      doc.line(m, y + 2, pw - m, y + 2);
      y += 8;

      entries.forEach((entry, idx) => {
        // Estimate height needed for this entry
        const estimatedH = 18
          + (entry.summary ? 8 : 0)
          + (entry.fields ? Object.keys(entry.fields).length * 5 : 0);
        pageBreak(Math.min(estimatedH, 40));

        const colors = typeColors[entry.type] || typeColors.note;

        // ── Type badge (pill)
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6.5);
        const tag = renderTypeLabel(entry.type).toUpperCase();
        const tagW = doc.getTextWidth(tag) + 4;
        const tagH = 4;
        doc.setFillColor(...colors.bg);
        doc.roundedRect(m, y - 3, tagW, tagH, 1.2, 1.2, "F");
        doc.setTextColor(...colors.text);
        doc.text(tag, m + 2, y - 0.5);

        // ── Entry number right of badge
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(...dark);
        const titleX = m + tagW + 3;
        const titleMaxW = cw - tagW - 3;
        const entryTitleLines = doc.splitTextToSize(`${idx + 1}. ${entry.title}`, titleMaxW);
        doc.text(entryTitleLines, titleX, y);
        y += entryTitleLines.length * 4.5 + 1.5;

        // Timestamp + source
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(...light);
        let subline = formatTimestamp(entry.createdAt);
        if (entry.source) subline += `  ·  ${entry.source}`;
        doc.text(subline, m + 4, y);
        y += 4.5;

        // Summary (skip if it duplicates the title)
        const titleBase = entry.title.replace(/\.{3}$/, "");
        const summaryDuplicatesTitle =
          entry.summary === entry.title ||
          (entry.title.endsWith("...") && entry.summary?.startsWith(titleBase));
        if (entry.summary && !summaryDuplicatesTitle) {
          pageBreak(8);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8.5);
          doc.setTextColor(...dark);
          const lines = doc.splitTextToSize(entry.summary, cw - 4);
          doc.text(lines, m + 4, y);
          y += lines.length * 3.8 + 1.5;
        }

        // Fields as key: value pairs
        if (entry.fields && Object.keys(entry.fields).length > 0) {
          pageBreak(6);
          y += 1;
          for (const [key, value] of Object.entries(entry.fields)) {
            pageBreak(5);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(7.5);
            doc.setTextColor(...mid);
            const lbl = `${key}:  `;
            doc.text(lbl, m + 4, y);
            const lw = doc.getTextWidth(lbl);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...dark);
            const vLines = doc.splitTextToSize(String(value), cw - 6 - lw);
            doc.text(vLines, m + 4 + lw, y);
            y += vLines.length * 3.5 + 1;
          }
        }

        y += 4;

        // Separator between entries
        if (idx < entries.length - 1) {
          pageBreak(3);
          doc.setDrawColor(230, 232, 236);
          doc.setLineWidth(0.15);
          doc.line(m, y - 1.5, pw - m, y - 1.5);
          y += 4;
        }
      });
    }

    // Apply header/footer chrome to all pages
    applyPageChrome();

    return doc;
  });
}

/* ─── Clear Confirmation Dialog ─── */
function ClearConfirmDialog({
  open,
  onConfirm,
  onCancel,
  entryCount,
}: {
  open: boolean;
  onConfirm: () => void;
  onCancel: () => void;
  entryCount: number;
}) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onCancel();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onCancel]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "var(--overlay-backdrop)" }}
      onClick={(e) => { if (e.target === e.currentTarget) onCancel(); }}
    >
      <div
        className="w-full max-w-sm rounded-xl p-5 space-y-4"
        style={{
          background: "var(--card)",
          border: "1px solid var(--border)",
          boxShadow: "0 16px 48px rgba(0,0,0,0.2)",
        }}
      >
        <div>
          <h3 className="text-base font-semibold text-[var(--foreground)]">Clear report?</h3>
          <p className="text-sm text-[var(--muted-foreground)] mt-1">
            This will remove {entryCount} {entryCount === 1 ? "entry" : "entries"} and reset all fields. Saved data will be deleted from this browser.
          </p>
        </div>
        <div className="flex gap-2 justify-end">
          <button
            onClick={onCancel}
            className="px-3 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:bg-[var(--accent)]"
          >
            Cancel
          </button>
          <button
            onClick={onConfirm}
            className="px-3 py-2 rounded-md text-sm font-medium bg-[var(--destructive)] text-white"
          >
            Clear everything
          </button>
        </div>
      </div>
    </div>
  );
}

/* ─── Autosave Indicator ─── */
function AutosaveIndicator({ lastSavedAt }: { lastSavedAt: string | null }) {
  const [label, setLabel] = useState("");

  useEffect(() => {
    if (!lastSavedAt) return;
    function update() {
      const diff = Date.now() - new Date(lastSavedAt!).getTime();
      if (diff < 5000) setLabel("Saved");
      else if (diff < 60000) setLabel(`Saved ${Math.floor(diff / 1000)}s ago`);
      else setLabel(`Saved ${Math.floor(diff / 60000)}m ago`);
    }
    update();
    const id = setInterval(update, 10000);
    return () => clearInterval(id);
  }, [lastSavedAt]);

  if (!lastSavedAt || !label) return null;

  return (
    <span className="text-xs text-[var(--muted-foreground)] flex items-center gap-1">
      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="20 6 9 17 4 12" />
      </svg>
      {label}
    </span>
  );
}

export default function JobReportBuilder() {
  const { meta, entries, storageStatus, updateMeta, addEntry, removeEntry, clearAll } =
    useJobReport();

  const [noteText, setNoteText] = useState("");
  const [paramName, setParamName] = useState("");
  const [oldValue, setOldValue] = useState("");
  const [newValue, setNewValue] = useState("");
  const [shareStatus, setShareStatus] = useState("");
  const [clearDialogOpen, setClearDialogOpen] = useState(false);

  const handleClearConfirm = useCallback(() => {
    clearAll();
    setClearDialogOpen(false);
  }, [clearAll]);

  const reportText = useMemo(
    () =>
      buildTextReport(
        meta.reportTitle,
        meta.siteName,
        meta.equipment,
        meta.technician,
        entries
      ),
    [meta, entries]
  );

  const reportSummary = useMemo(() => {
    return `${meta.reportTitle || "Field Tech Report"} | ${entries.length} entries | ${meta.siteName || "No site specified"}`;
  }, [meta.reportTitle, meta.siteName, entries.length]);

  function handleAddNote() {
    const trimmed = noteText.trim();
    if (!trimmed) return;
    addEntry({
      type: "note",
      title: trimmed.length > 72 ? `${trimmed.slice(0, 72)}...` : trimmed,
      summary: trimmed,
      source: "Manual note",
    });
    setNoteText("");
  }

  function handleAddParameterChange() {
    const param = paramName.trim();
    if (!param || !oldValue.trim() || !newValue.trim()) return;

    addEntry({
      type: "parameter-change",
      title: `Parameter ${param} adjusted`,
      summary: `Changed from ${oldValue} to ${newValue}`,
      source: "Manual parameter log",
      fields: {
        Parameter: param,
        "Old Value": oldValue.trim(),
        "New Value": newValue.trim(),
      },
    });

    setParamName("");
    setOldValue("");
    setNewValue("");
  }

  function handleExportText() {
    const safeTitle = (meta.reportTitle || "field-tech-report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-");
    downloadFile(`${safeTitle}.txt`, reportText, "text/plain");
  }

  function handleExportJson() {
    const payload = {
      exportedAt: new Date().toISOString(),
      meta,
      entries,
    };
    const safeTitle = (meta.reportTitle || "field-tech-report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-");
    downloadFile(`${safeTitle}.json`, JSON.stringify(payload, null, 2), "application/json");
  }

  const [pdfExporting, setPdfExporting] = useState(false);

  async function handleExportPdf() {
    setPdfExporting(true);
    try {
      const doc = await buildPdf(
        meta.reportTitle,
        meta.siteName,
        meta.equipment,
        meta.technician,
        entries
      );
      const dateStr = new Date().toISOString().slice(0, 10);
      const safeTitle = (meta.reportTitle || "Field-Tech-Report")
        .replace(/[^a-zA-Z0-9\s-]/g, "")
        .trim()
        .replace(/\s+/g, "-");
      doc.save(`${safeTitle}-${dateStr}.pdf`);
    } catch {
      setShareStatus("Failed to generate PDF. Please try again.");
    } finally {
      setPdfExporting(false);
    }
  }

  async function handleShare() {
    try {
      if (navigator.share) {
        await navigator.share({
          title: meta.reportTitle || "Field Tech Report",
          text: `${reportSummary}\n\n${reportText}`,
        });
        setShareStatus("Shared successfully.");
        return;
      }

      await navigator.clipboard.writeText(reportText);
      setShareStatus("Share not available on this browser. Report copied to clipboard.");
    } catch {
      setShareStatus("Could not share report on this device/browser.");
    }
  }

  return (
    <div className="space-y-6">
      <section className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-5 space-y-4">
        <h2 className="text-lg font-semibold">Report Details</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor="report-title" className="block text-sm font-medium mb-1.5">Report title</label>
            <input
              id="report-title"
              value={meta.reportTitle}
              onChange={(event) => updateMeta({ reportTitle: event.target.value })}
              placeholder="e.g., AHU-3 Startup Report"
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
          </div>
          <div>
            <label htmlFor="site-name" className="block text-sm font-medium mb-1.5">Site name</label>
            <input
              id="site-name"
              value={meta.siteName}
              onChange={(event) => updateMeta({ siteName: event.target.value })}
              placeholder="e.g., Building 400"
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
          </div>
          <div>
            <label htmlFor="equipment" className="block text-sm font-medium mb-1.5">Equipment tag / asset</label>
            <input
              id="equipment"
              value={meta.equipment}
              onChange={(event) => updateMeta({ equipment: event.target.value })}
              placeholder="e.g., AHU-3, VFD-12"
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
          </div>
          <div>
            <label htmlFor="technician" className="block text-sm font-medium mb-1.5">Technician name</label>
            <input
              id="technician"
              value={meta.technician}
              onChange={(event) => updateMeta({ technician: event.target.value })}
              placeholder="Your name"
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
          </div>
        </div>
      </section>

      <section className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-5 space-y-3">
        <h2 className="text-lg font-semibold">Add Findings</h2>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="space-y-2">
            <label htmlFor="quick-note" className="text-sm font-medium">Quick Note</label>
            <textarea
              id="quick-note"
              value={noteText}
              onChange={(event) => setNoteText(event.target.value)}
              rows={4}
              placeholder="Add observed behavior, root cause notes, or work performed."
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
            <button
              onClick={handleAddNote}
              className="px-3 py-2 rounded-md text-sm font-medium bg-[var(--primary)] text-[var(--primary-foreground)] min-h-11"
            >
              Add note
            </button>
          </div>

          <div className="space-y-2">
            <label htmlFor="param-id" className="text-sm font-medium">Parameter Change</label>
            <input
              id="param-id"
              value={paramName}
              onChange={(event) => setParamName(event.target.value)}
              placeholder="Parameter ID (e.g., 01.07)"
              className="w-full px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
            />
            <div className="grid grid-cols-2 gap-2">
              <input
                value={oldValue}
                onChange={(event) => setOldValue(event.target.value)}
                placeholder="Old value"
                aria-label="Old value"
                className="px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
              />
              <input
                value={newValue}
                onChange={(event) => setNewValue(event.target.value)}
                placeholder="New value"
                aria-label="New value"
                className="px-3 py-2.5 rounded-md bg-[var(--input)] border border-[var(--border)] text-[var(--foreground)] placeholder:text-[var(--muted-foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--ring)]"
              />
            </div>
            <button
              onClick={handleAddParameterChange}
              className="px-3 py-2 rounded-md text-sm font-medium bg-[var(--primary)] text-[var(--primary-foreground)] min-h-11"
            >
              Add parameter change
            </button>
          </div>
        </div>
      </section>

      <ClearConfirmDialog
        open={clearDialogOpen}
        onConfirm={handleClearConfirm}
        onCancel={() => setClearDialogOpen(false)}
        entryCount={entries.length}
      />

      <section className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-5 space-y-3">
        <div className="flex flex-wrap items-center gap-2 justify-between">
          <div className="flex items-center gap-3">
            <h2 className="text-lg font-semibold">Captured Entries ({entries.length})</h2>
            <AutosaveIndicator lastSavedAt={storageStatus.lastSavedAt} />
          </div>
          <div className="flex items-center gap-2">
            {storageStatus.sizeBytes > 0 && (
              <span
                className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium"
                style={{
                  background: "var(--accent)",
                  color: "var(--muted-foreground)",
                }}
              >
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                </svg>
                {storageStatus.sizeLabel}
              </span>
            )}
            <button
              onClick={() => setClearDialogOpen(true)}
              disabled={entries.length === 0 && !meta.siteName && !meta.equipment && !meta.technician}
              className="px-3 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:bg-[var(--accent)] disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Clear all
            </button>
          </div>
        </div>

        {entries.length === 0 && (
          <div className="rounded-lg border border-dashed border-[var(--border)] p-6 text-center">
            <p className="text-sm font-medium text-[var(--muted-foreground)]">No findings captured yet</p>
            <p className="text-xs text-[var(--muted-foreground)] mt-1">Add from tools or use the forms above.</p>
          </div>
        )}

        {entries.map((entry) => (
          <article
            key={entry.id}
            className="rounded-lg border border-[var(--border)] p-4 space-y-2"
          >
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs uppercase tracking-wide text-[var(--muted-foreground)]">
                  {renderTypeLabel(entry.type)}
                </p>
                <h3 className="font-medium">{entry.title}</h3>
              </div>
              <button
                onClick={() => removeEntry(entry.id)}
                className="text-xs px-2 py-1 rounded border border-[var(--border)] hover:bg-[var(--accent)]"
              >
                Remove
              </button>
            </div>
            <p className="text-xs text-[var(--muted-foreground)]">
              {formatTimestamp(entry.createdAt)}
              {entry.source ? ` • ${entry.source}` : ""}
            </p>
            {entry.summary && entry.summary !== entry.title && (
              <p className="text-sm text-[var(--muted-foreground)]">{entry.summary}</p>
            )}
            {entry.fields && Object.keys(entry.fields).length > 0 && (
              <div className="text-sm grid grid-cols-1 md:grid-cols-2 gap-2">
                {Object.entries(entry.fields).map(([key, value]) => (
                  <p key={key} className="text-[var(--muted-foreground)]">
                    <span className="font-medium text-[var(--foreground)]">{key}:</span>{" "}
                    {value}
                  </p>
                ))}
              </div>
            )}
          </article>
        ))}
      </section>

      <section className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-5 space-y-3">
        <h2 className="text-lg font-semibold">Export / Share</h2>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handleExportPdf}
            disabled={pdfExporting}
            className="px-3 py-2 rounded-md text-sm font-medium bg-[var(--primary)] text-[var(--primary-foreground)] min-h-11 disabled:opacity-60"
          >
            {pdfExporting ? "Generating…" : "Export PDF"}
          </button>
          <button
            onClick={handleExportText}
            className="px-3 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:bg-[var(--accent)]"
          >
            Export TXT
          </button>
          <button
            onClick={handleExportJson}
            className="px-3 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:bg-[var(--accent)]"
          >
            Export JSON
          </button>
          <button
            onClick={handleShare}
            className="px-3 py-2 rounded-md text-sm font-medium border border-[var(--border)] hover:bg-[var(--accent)]"
          >
            Share / Copy
          </button>
        </div>
        {shareStatus && (
          <p className="text-sm text-[var(--muted-foreground)]">{shareStatus}</p>
        )}
      </section>
    </div>
  );
}
